### ISSUE TITLE
Long-running commands crash the kernel

### ISSUE THREAD

**Issue by mcaceresb** [kylebarron/stata_kernel#114]
#### Code Sample

```stata
sleep 20000
```
#### Problem description

Crashes.

#### Expected Output

Not crashing.

#### Debugging log

```
tail ~/.stata_kernel_cache/console_debug.log -n5

. `08a286cef0dc100f5df674f2b5353f29'
. sleep 20000
`74d9065a0d853acfb9ba909e390bc528'
sleep 20000
```

#### Package Version

```
Name: stata-kernel
Version: 1.4.1
Summary: A Jupyter kernel for Stata. Works with Windows, macOS, and Linux. Preserves program state.
Home-page: https://github.com/kylebarron/stata_kernel
Author: Kyle Barron
Author-email: barronk@mit.edu
License: GPLv3
Location: /usr/lib/python3.6/site-packages
Requires: beautifulsoup4, jupyter-client, IPython, ipykernel, pandas, pillow, pexpect, pygments, regex
Required-by: 
```

**Comment by kylebarron** [comment]
Should we turn it 100% off already, or to a decently high number while we root out additional bugs?

**Comment by kylebarron** [comment]
Actually the timeout is currently only 5 seconds:
https://github.com/kylebarron/stata_kernel/blob/6d11594c00f789c98f8530273d5cd5b53525b04c/stata_kernel/stata_session.py#L230

This should be increased at least to a few minutes for now?

**Comment by mcaceresb** [comment]
Well, in it's fine if it stays on but for now but it should eventually be off entirely.

**Comment by kylebarron** [comment]
Agreed, but for now it should at least be more than 5 seconds. I set that when I was doing constant debugging. I'd be happy to put it at like 5 minutes now.

**Comment by kylebarron** [comment]
Fixed with https://github.com/kylebarron/stata_kernel/commit/8bf9d7d24328b4c86cd93ddf56f7382e27925440

I turned off the timeout completely for the main `expect`. I think this is reasonable because the known unresolved issues don't have anything to deal with this. Specifically, the `expect` that has failing `--more--` behavior is determined by a [separate function](https://github.com/kylebarron/stata_kernel/blob/8bf9d7d24328b4c86cd93ddf56f7382e27925440/stata_kernel/stata_session.py#L331-L358). We hit `--more--` 100% of the time, we just have issues sending `--break--`.
