### ISSUE TITLE
Extra space after count

### ISSUE THREAD

**Issue by peterhickmanj** [kylebarron/stata_kernel#121]
#### Code Sample

```stata
sysuse auto, clear
count if mpg == 14
```

#### Problem description

The output of `count` is highlighted with extra spaces before the output.

#### Expected Output

Only the 6 should be highlighted

#### Debugging log

My stata_kernel version is 1.4.1

**Comment by kylebarron** [comment]
@peterhickmanj 

I took a quick look at this. The Stata output for `count` seems to always include two leading spaces. I personally would consider this a Stata bug. For 99% of commands, there are no leading spaces. I don't necessarily want to remove all leading whitespace from all lines, because I don't know when it's intended, such as to line up a table. 

![image](https://user-images.githubusercontent.com/15164633/44624311-7621e780-a89f-11e8-963f-1c9d5f5762f2.png)

**Comment by kylebarron** [comment]
I'm going to close this, for lack of a better solution and for my belief that it's a Stata issue that I shouldn't mess with. Feel free to comment further.
