### ISSUE TITLE
Mention nteract electron app in docs

### ISSUE THREAD

**Issue by kylebarron** [kylebarron/stata_kernel#129]

**Comment by kylebarron** [comment]
@mcaceresb I know you don't love electron apps but it still looks cool.

Also uses codemirror syntax highlighting, so I should get around to submitting a Stata PR for that.

![image](https://user-images.githubusercontent.com/15164633/45037374-d72e8580-b02c-11e8-9da2-ff9ae18e10b2.png)

**Comment by mcaceresb** [comment]
Well, I don't dislike electron apps in the abstract! My issue is that I'm usually comparing it with something that has a very small memory footprint and little to no lag. For something like a text editor, where the main thing I want is to edit text, all the bells and whistles, while really nice and I like and want them, don't justify the trade-off _for me specifically_.

In this case, tho, I'm 100% with you that nteract looks awesome! Because it's not really that different from qtconsole in terms of lag, and I'm already willing to make that trade-off relative to console apps. It's also way better than notebooks in my browser (which I kind of really dislike). Since it looks better than qtsoncole, is equally minimal in design, and supports HTML, from my POV it's basically just a much better version. Which, again, is pretty cool.

**Comment by kylebarron** [comment]
Of course. I was mostly teasing!

In the medium term I want to work more on Hydrogen to improve its import and export of Jupyter notebook `.ipynb` files.

Yeah I'll look into codemirror. Ties de Kok has a file he uses, shared in #4, but he asks users to do a [hack](https://github.com/TiesdeKok/ipystata#syntax-highlighting) to get syntax highlighting to work in the notebook. I'll submit a PR to codemirror, but that might take a while to get into the released versions of Notebook and Nteract, especially since it sounds like Codemirror is working on a new major version: https://news.ycombinator.com/item?id=17858672

**Comment by mcaceresb** [comment]
Clearly the solution is to bundle the kernel with your forked version of codemirror.

**Comment by kylebarron** [comment]
I can't tell if that's serious... Wouldn't that be hard because the notebook and nteract wouldn't see my forked version that comes with the kernel?

**Comment by mcaceresb** [comment]
I guess teasing is a one-way street ;)

No, I wasn't really serious. I think it'd be easier to write instructions for the user rather than try to bundle a forked version.

**Comment by kylebarron** [comment]
Haha I should use /s to delimit my sarcasm more often... I'm too gullible when reading text comments

**Comment by kylebarron** [comment]
It doesn't appear that nteract supports autocompletion though...

**Comment by mcaceresb** [comment]
Ctrl+space does it for me.

**Comment by kylebarron** [comment]
Ah cool. I figured it must exist...
