### ISSUE TITLE
Expand scope of autocomplete

### ISSUE THREAD

**Issue by kylebarron** [kylebarron/stata_kernel#160]
@mcaceresb I know we talked about this before and I had said that I wasn't interested in adding much more to autocomplete, but I'm slowly changing my mind. In the global scope, i.e. not after `` ` ``, `$`, etc, I think it would be helpful to (in addition to variable names) also autocomplete

- user-defined programs
- matrix names

Probably more that I haven't thought of. I think we do autocomplete for scalars?

**Comment by mcaceresb** [comment]
Matrices can only appear in certain environments (`matrix` or `svmat`, for instance). We do the former but not anything else. Scalars are...annoying. Yes, we do scalars for `scalar` and `scalar(`, but Stata falls back to scalars if a variable isn't found, which blows my mind, but whatever.

Anyway, all this means that we shouldn't add matrices to the global scope, but adding scalars to the global scope might make sense.

For user programs it's a bit odd to add them to the global scope since you can't use them everywhere.

```
gen new = <tab>
```

And seeing program names seems counter-intuitive to me. I'd say doing programs at the start of line (maybe even instead of variable names) or after certain symbols, like `:` (or `||`?), along with anything that ends up in the global scope (always hedging for qui/cap/noi).

**Comment by kylebarron** [comment]
Well you can only define them in those instances, but can't you do something like `di A[1,1]` anywhere?

You're right that it would make more sense to autocomplete programs only when there's nothing else on the line or after certain characters. I'd say even without a `:`, if there's just `qui/cap/noi` on the current line, also autocomplete program names.

**Comment by mcaceresb** [comment]
By convention, several Stata programs allow 

```
program, args: otherProgram, args
```

e.g. `by` or `bootstrap`. But we can do without. Mmm... It seems the matrix thing is like scalars: If a variable by that name exists, those things fail. Otherwise you can use it anywhere as well. Didn't realize.

**Comment by kylebarron** [comment]
> But we can do without

Yes

**Comment by kylebarron** [comment]
I'm going to close this for now, because I don't really have any interest in implementing this. Reopen if desired.
