### ISSUE TITLE
add automation mode for linux

### ISSUE THREAD

**Issue by alikazemkhanloo** [kylebarron/stata_kernel#218]
What is the problem with automation in Linux? console mode fails to do some commands like `graph`, `browse`, etc.
Will it be available some time?

**Comment by kylebarron** [comment]
No. There's no such thing as Stata Automation on Linux. Automation is Stata's officially-supported way of communicating with Stata, but they only support Windows and Mac. To get around that, this package controls a console version of Stata. You should be able to get basically all the same functionality. 

You can't use `browse`, because Stata is running in a console, but you can use the [`%browse`](https://kylebarron.github.io/stata_kernel/using_stata_kernel/magics/#browse) magic. In Atom or Jupyter Notebook, that will show the data in a pretty format. 

Graphs should work though. If you can give a simple example of a graph that doesn't work, let me know.

**Comment by kylebarron** [comment]
The documentation should be updated a bit. A little further explanation of the execution mode was added: https://kylebarron.github.io/stata_kernel/getting_started/#execution_mode

I'm going to close this. If you find an example where a graph command doesn't work, please open a new issue.

**Comment by kylebarron** [comment]
Can you give some example with either of those not working?

If you're using Jupyter console, they won't work, otherwise they should

**Comment by alikazemkhanloo** [comment]
I was using the package alongside with the Hydrogen in the Atom. as far as I remember, the output was something like `command browse not found` or `command graph no found`.

I was trying to run `graph box ...`.

**Comment by kylebarron** [comment]
Getting `command browse not found` means that you tried to run `browse`. If you precede that with a %, `%browse` and run that by itself, it'll work. 

I need an explicit example to say why the graph didn't work. Maybe it's a Stata syntax error.

**Comment by alikazemkhanloo** [comment]
Ok. I will try it again and send the output here.
