### ISSUE TITLE
Delete .stata_kernel_images folder on kernel shutdown

### ISSUE THREAD

**Issue by kylebarron** [kylebarron/stata_kernel#24]

**Comment by kylebarron** [comment]
Yes I agree, but I was thinking of the dua model, and I'm not sure it would be ok to arbitrarily save images in tmp (likewise with the cross-console history file, not sure that can go in ~ by default. Maybe I could put this setting in the configuration.

**Comment by mcaceresb** [comment]
The "tmp" folder created via `tempfile` is only readable and writeable by the user that makes it, AFAIK. I did ask about this when I started work because the DUA model says all the things must be in the user's DUA folder. However, SAS and Stata create temporary files in the system's temporary directory all the time. I was told that was OK.

Nevertheless, an option to specify the images cache directory would certainly be nice.

**Comment by kylebarron** [comment]
I'm not sure it's necessary to delete the cache directory anymore, as long as it's always in the same place and now possible to be user defined.
