### ISSUE TITLE
Graphs disappear after closing session

### ISSUE THREAD

**Issue by v-marinkov** [kylebarron/stata_kernel#304]
#### Problem description
Any time a Jupyter notebook is closed and reopened, all figures disappear and instead show:
`This front-end cannot display the desired image type`
I presume it has to do something with the temporary global variable `graph_counter` which gets reset after the kernel is restarted. This is what the kernel does whenever I call `scatter`
`noi gr export /home/viktor/.stata_kernel_cache/graph${stata_kernel_graph_counter}.svg, width(600) replace`

#### Expected behavior
I would expect that graphs are stored within the `ipynb` file itself. This used to be case with `ipystata`. If not, at least there should be notebook-specific folders containing the corresponding graphs and not a common `cache` folder where graphs get replaced once the counter resets.

#### Other information
- Ubuntu 18.10
- Stata MP 14.2
- Package version: 1.5.x but after upgrading to 1.10.5, the behavior is still the same

**Comment by kylebarron** [comment]
I think this is because SVG images are currently saved in `<iframe>` tags. If we took out that tag, I think it would work fine. That tag is there because of a defect in Stata's SVG image generation. See https://github.com/kylebarron/stata_kernel/issues/234

The easiest workaround is to set the image format to PNG. 

@mcaceresb

**Comment by v-marinkov** [comment]
Actually, it seems to work fine after a restart. Perhaps I hadn't fully reloaded the updated stata kernel. Thanks

**Comment by kylebarron** [comment]
Weird, good to know
