### ISSUE TITLE
Add stata_kernel to conda-forge?

### ISSUE THREAD

**Issue by BoPeng** [kylebarron/stata_kernel#311]
Is there any plan to add stata_kernel to conda-forge? I plan to add [`sos-stata`](https://github.com/vatlab/sos-stata) to conda-forge but found that `stata_kernel` is not currently available in conda. Thanks.

**Comment by kylebarron** [comment]
I looked at this a while ago but I wasn't able to figure out the build process for conda packages. At this point there are no plans to make a conda package, and the dependencies are simple enough that using pip shouldn't be a problem

**Comment by stanmart** [comment]
I would be willing to try building a conda-forge recipe for stata_kernel. I you are okay with it I would take a stab at it.

**Comment by kylebarron** [comment]
A different person can provide the conda-forge package than who builds the pip package.

**Comment by stanmart** [comment]
I've created a conda recipe and it is _almost_ alright: [PR link](https://github.com/conda-forge/staged-recipes/pull/12872/)

The one remaining issue is that CI tests are failing on `pip check` as pip cannot find jupyter amongst the installed packages. The reason is that jupyter is actually a metapackage consisting of the following packages:
 - notebook
 - qtconsole
 - jupyter-console
 - nbconvert
 - ipykernel
 - ipywidgets

and the way pip and conda installs metapackages is slightly different. Both install the constituent packages, but pip also adds the metapackage's name to the list of installed packages, while conda does not (it adds it to the environment specs instead). The result is that a pip check will not list jupyter if it is installed using conda even if all of its parts are succesfully installed. I see three ways to solve this:

 - Remove the pip check from the tests section. This would not require modifying anything in the package itself, and it does not seem like an especially important test (if there is a problem with dependencies the previous install step or the next import step should fail anyways)
 - Instead of listing jupyter as a stata_kernel requirement list the six packages in that metapackage separately. The advantage is that it would make it more explicit what exactly stata_kernel depends on, but on the other hand would take away from the convenience of saying that it requires a full jupyter installation. I don't think it's worth doing this over the first option.
 - Streamline the requirements, as the only package stata_kernel truly depends on out of the above six is ipykernel (See #361 for details). I like this option the most, but ofc I understand if you want he whole jupyter as a dependency.

What do you think?

**Comment by BoPeng** [comment]
Do not know the answer but there are plenty of jupyter kernels on conda-forge and you can check how they handle this issue.

**Comment by stanmart** [comment]
Thanks, good idea. After a quick review I found the following.

 - There are kernels which are written in the target language (like kernels for R and Julia). For these conda-forge manifests do not specify any python dependencies either, and it is up to the user to have Python and a Jupyter that can communicate with these kernels.
 - There are packages that are ipython-based wrapper kernels (stata_kernel also falls in this category). These of course depend on the ipykernel package. Examples are the [metakernel](https://github.com/Calysto/metakernel)-based [Octave](https://github.com/Calysto/octave_kernel/blob/master/setup.py), [Matlab](https://github.com/Calysto/octave_kernel/blob/master/setup.py), [bash](https://github.com/Calysto/calysto_bash/blob/master/setup.py) or [SAS](https://github.com/sassoftware/sas_kernel) kernels. Most often they only specify ipykernel (and thus in turn also ipython and jupyter_client) as a dependency instead of the whole jupyter metapackage. There are exceptions though, such as [agda-kernel](https://github.com/lclem/agda-kernel) that depends on the jupyter metapackage (or rather, specifies it as a dependency, but most likely still only depend on ipykernel).

Based on these I still think removing jupyter from the dependencies and modifying the docs accordingly (note that users may also need to install jupyter/jupyterlab) is the best solution - not just to the conda-forge packaging issue but in general as well. I can submit a PR with these changes if @kylebarron agrees with them. If not then I will just stick to option one as that does not involve changing anything in stata_kernel.

**Comment by kylebarron** [comment]
I think removing jupyter and keeping only `ipykernel` is fine. I originally listed the entire jupyter metapackage to make things easier for people who had never touched Python before.

**Comment by kylebarron** [comment]
Closing as fixed, thanks @stanmart!
