### ISSUE TITLE
Kernel is starting in wrong version of stata

### ISSUE THREAD

**Issue by po4dun** [kylebarron/stata_kernel#341]
Hi
I have both stata12 und stata15 installed. In .stata_kernel.conf I set the path to stata15, however the kernel starts only version 12. Where else can I configure which version to run? #313 was similar but never answered.

Thanks

- Windows 10
- 1.10.5

**Comment by kylebarron** [comment]
On Windows the way Stata is started is a little different
https://github.com/kylebarron/stata_kernel/blob/170b6ba43dbfccceb0afac30d2e105589bf06ef5/stata_kernel/stata_session.py#L154

Instead of using the path, it uses the stata executable that was "registered"
https://kylebarron.dev/stata_kernel/getting_started/#prerequisites

So I think you need to unregister the Stata 12 executable and register the Stata 15 executable. Just registering Stata 15 might successfully overwrite Stata 12 but I'm not sure

**Comment by po4dun** [comment]
Unregistering/registering didn't work, but I just renamed the Stata12 program folder and it worked, thanks!
