### ISSUE TITLE
User `appdirs` instead of user's home folder for default locations?

### ISSUE THREAD

**Issue by mcaceresb** [kylebarron/stata_kernel#61]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Instead of `~/.stata_kernel.conf` and `~/.stata_kernel_cache` for the defaults, it  might make more sense to do
```
import appdirs
import os
os.path.join(appdirs.user_config_dir(), 'stata_kernel.conf')
os.path.join(appdirs.appdirs.user_cache_dir(), 'stata_kernel_cache')
```

I don't feel too strongly about `~/.stata_kernel.conf` because otherwise it might be hard for people to find it across various systems, but I think moving `~/.stata_kernel_cache` might make more sense.

**Describe alternatives you've considered**
N/A

**Additional context**
I think that it's better to use system folders designed for such things.

**Comment by kylebarron** [comment]
Is it guaranteed that the appdirs location is user writable? 

Also I don't want to make it too difficult to find the app dir. Especially because I'm guessing that there will be edge cases that other people find and I'd want to make it easy for them to send me the log file. 

In https://github.com/kylebarron/stata_kernel/commit/f15a98f7736cdc0e8fd424fe3aef3e9dd53addd9 I set _all_ the output from the spawned instance of Stata to go to the cache dir, which should make it easier to get debug logs.

**Comment by mcaceresb** [comment]
If this will only ever have a config file and a dir I think that's fine.

**Comment by kylebarron** [comment]
I think everything I ever put will go into `~/.stata_kernel_cache`. Potentially far down the road that could include some small intermediate datasets. I.e. save the first 100 rows of a data file to disk, open them in Python for interactive browsing. But that's not my concern for a while.
